name: Deploy Flask Application to Linode VM

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Repository to Linode VM
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo mkdir -p /path/to/your/app
            rsync -az . /path/to/your/app

      - name: Build Docker Image
        run: |
          cd /path/to/your/app
          docker build -t my-flask-application:${{ github.sha }} -t 

      - name: Deploy Docker Image
        run: |
          docker-compose up -d
          docker image prune -f

  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait for Application
        uses: jwalton/wait-for-it@master
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          port: 8000
          timeout: 300s