name: Deploy Flask Application to Linode VM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Linode VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Copy Repository to Linode VM
        run: |
          sudo mkdir -p /home/test
          rsync -az . /home/test

      - name: Build Docker Image
        run: |
          cd /home/test
          docker build -t my-flask-application:${{ github.sha }} -t 

      - name: Deploy Docker Image
        run: |
          docker-compose up -d
          docker image prune -f

  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait for Application
        uses: jwalton/wait-for-it@master
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          port: 8000
          timeout: 300s