name: Deploy Flask Application to Linode VM
run-name: ${{ github.actor }} is testing out more actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository to Linode VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

      - name: Change to temp Directory
        run: |
          mkdir /tmp/test
          cd /tmp/test

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy Repository to Application Directory
        run: |
          chmod 777 /home/test
          mkdir /home/test
          rsync -az /tmp/test /home/test

      - name: Build Docker Image
        run: |
          cd /home/test
          docker build -t my-flask-application:${{ github.sha }} -t 

      - name: Deploy Docker Image
        run: |
          docker-compose up -d
          docker image prune -f

  health-check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Wait for Application
        uses: jwalton/wait-for-it@master
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          port: 8000
          timeout: 300s