name: Deploy Flask Application to Linode VM
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Repository to Linode VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rsync -az $GITHUB_WORKSPACE/ /home/test2
            cd /home/test2
            docker build -t my-flask-application:${{ github.sha }}
            docker-compose up -d
            docker image prune -f


  # health-check:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   steps:
  #     - name: Wait for Application
  #       uses: jwalton/wait-for-it@master
  #       with:
  #         host: ${{ secrets.LINODE_VM_IP }}
  #         port: 8000
  #         timeout: 300s